/**
 * Per-task prompt construction for DAG-driven generation.
 *
 * The generation unit is NOT "the whole backend" — it is one task in a
 * dependency graph (models → schemas/security → routers → app). Each
 * task's prompt is a pure function of the blueprint slice it needs:
 * narrow scope, explicit file ownership, previous artifacts readable.
 *
 * Determinism rules: no timestamps, no randomness, no session state.
 * Identical blueprints produce identical prompts (and identical DAGs).
 */
import { stableStringify } from "@spec/core"
import type { BackendBlueprint, BlueprintRoute } from "./blueprint"

const SHARED_INVARIANTS = `## Global invariants (hold for every task)
- Entity JSON keys are the field names EXACTLY as declared (camelCase stays camelCase).
- ref fields serialize as the referenced row's id string.
- Implicit columns (created_at on every entity, password_hash on the auth
  principal) are NEVER serialized; created_at only orders lists (ascending).
- list returns EVERY row of the entity (including the requesting principal
  when applicable) as a bare JSON array, ordered by created_at ascending.
- Fields with a declared default are omittable in create bodies; the
  default applies when omitted; optional-without-default stores null.
- Server generates uuid4 ids; id in request bodies is ignored.
- Error bodies (exact): 401 {"detail": "Not authenticated"} ·
  404 {"detail": "Not found"} (unknown id AND dangling refs) ·
  409 {"detail": "Already exists"} (unique violations) · 422 = FastAPI default.
- Path parameters are named exactly \`id\`.
- Do not add any route, file or path beyond your scope — the conformance
  suite asserts STRICT OpenAPI equality.
- SQLite-compatible SQL only (tests run on SQLite).`

function routeTable(routes: BlueprintRoute[]): string {
  return routes
    .map((r) => `| ${r.method} | ${r.path} | ${r.status} | ${r.auth ? "bearer" : "public"} | ${r.operation} |`)
    .join("\n")
}

function taskHeader(task: string, scope: string[], context: string[]): string {
  return `You are executing ONE TASK of a larger, compiler-planned generation.

# Task: ${task}

The specification compiler derived this task from the user's
specification. Files from previous tasks already exist in this workspace
and are part of the same application: READ them for context, match their
conventions, and do NOT modify anything outside your scope.

- Your scope (create/modify ONLY these): ${scope.join(", ")}
- Already generated by previous tasks (read-only for you): ${
    context.length > 0 ? context.join(", ") : "—"
  }`
}

export interface TaskPromptInput {
  blueprint: BackendBlueprint
  scope: string[]
  context: string[]
}

export function projectPrompt(bp: BackendBlueprint, ctx: TaskPromptInput): string {
  const deps = Object.entries(bp.stack.dependencies)
    .map(([name, version]) => `"${name}==${version}"`)
    .join(",\n    ")
  const dev = Object.entries(bp.stack.dev)
    .map(([name, version]) => `"${name}==${version}"`)
    .join(",\n    ")
  return `${taskHeader("project skeleton", ctx.scope, ctx.context)}

Create the Python project skeleton for "${bp.app.title}".

## Requirements
- \`pyproject.toml\`: project name \`${bp.app.name.toLowerCase()}\`, version
  \`${bp.app.version}\`, installable (hatchling or setuptools),
  \`requires-python = "==${bp.stack.python}.*"\`, with EXACTLY these pinned
  dependencies (the stack is part of the specification — do not add,
  remove or float any version):
  \`\`\`toml
  dependencies = [
    ${deps},
  ]

  [project.optional-dependencies]
  dev = [
    ${dev},
  ]
  \`\`\`
  Do NOT add passlib (it crashes with bcrypt >= 5); bcrypt is already
  pinned.
- Package directory \`app/\` with \`app/__init__.py\`.
- A \`.gitignore\` covering caches and virtualenvs.

## App metadata
\`\`\`json
${stableStringify(bp.app)}
\`\`\``
}

export function modelsPrompt(bp: BackendBlueprint, ctx: TaskPromptInput): string {
  return `${taskHeader("data models", ctx.scope, ctx.context)}

Implement the SQLAlchemy models (\`app/models.py\`).

${SHARED_INVARIANTS}

## Entities (the complete data model)
\`\`\`json
${stableStringify(bp.entities)}
\`\`\`

## Requirements
- One class per entity; \`__tablename__\` = the blueprint's \`table\`
  (snake_case plural); columns = the blueprint's \`column\` names.
- \`id\`: string uuid primary key, server-side uuid4 default (Python-side
  default is fine).
- \`created_at\`: naive-UTC datetime column on EVERY entity, set once on
  insert (a shared mixin is idiomatic).
${bp.auth ? `- The principal \`${bp.auth.principal}\` additionally gets the implicit column \`${bp.auth.passwordColumn}\` (bcrypt hash).` : "- No auth in this specification: no password columns."}
- \`ref\` fields become string(36) columns with ForeignKey("<target table>.id").
- \`enum\` fields become string columns validated against their \`states\`;
  a lifecycle-bound enum column defaults to the lifecycle's initial state.
- Unique constraints for \`unique\` fields; nullable for \`optional\` fields.${
    bp.effects
      ? `
- ALSO generate the outbox table \`${bp.effects.eventsTable}\` with EXACTLY
  these columns: id (string uuid pk), event (string), payload (string
  holding a JSON object), created_at (naive-UTC datetime). Transitions
  with emit effects insert into it in-transaction; expose NO routes
  for it.`
      : ""
  }`
}

export function databasePrompt(bp: BackendBlueprint, ctx: TaskPromptInput): string {
  return `${taskHeader("database layer", ctx.scope, ctx.context)}

Implement the database/engine layer.

${SHARED_INVARIANTS}

## Database contract
\`\`\`json
${stableStringify(bp.database)}
\`\`\`

## Requirements
- \`app/config.py\`: settings object reading \`DATABASE_URL\` (pydantic-settings).
- \`app/database.py\`: engine + sessionmaker factory from a SQLAlchemy URL
  string; expose a \`get_db\` FastAPI dependency yielding a session.
- URL resolution order (pinned): explicit argument → \`DATABASE_URL\` env →
  \`${bp.database.fallback}\`. Values are ALWAYS SQLAlchemy URLs
  (\`sqlite:///...\`, \`postgresql+psycopg://...\`); normalize bare paths.
- Tables are created via \`Base.metadata.create_all(engine)\` at app
  startup (the app task wires this — export what it needs).`
}

export function schemasPrompt(bp: BackendBlueprint, ctx: TaskPromptInput): string {
  return `${taskHeader("pydantic schemas", ctx.scope, ctx.context)}

Implement the request/response schemas (\`app/schemas.py\`).

${SHARED_INVARIANTS}

## Entities
\`\`\`json
${stableStringify(bp.entities.map((e) => ({ name: e.name, fields: e.fields })))}
\`\`\`

## Requirements
- Per entity: a Create model (all fields except \`id\`; defaulted and
  optional fields omittable), an Update model (every field optional —
  partial PATCH semantics), and a response serializer producing EXACTLY
  the declared field names in responses (never password_hash/created_at).
- Field validation by type: string/int/boolean/uuid/email/datetime; ref
  fields are id strings; enum fields validate against their \`states\`.
- Lifecycle-bound state fields are EXCLUDED from Create and Update models
  entirely (the server assigns the initial state; PATCH ignores the field).
- Response serialization is contract-critical: keys and casing must match
  the declared field names exactly.`
}

export function securityPrompt(bp: BackendBlueprint, ctx: TaskPromptInput): string {
  return `${taskHeader("auth security", ctx.scope, ctx.context)}

Implement JWT/bcrypt security (\`app/security.py\`, \`app/deps.py\`).

${SHARED_INVARIANTS}

## Auth contract
\`\`\`json
${stableStringify({ auth: bp.auth, unauthenticated: bp.contract.errors.unauthenticated })}
\`\`\`

## Requirements
- Password hashing with the \`bcrypt\` package DIRECTLY (\`bcrypt.hashpw\` /
  \`bcrypt.checkpw\`) — do NOT use passlib (passlib 1.7.4 crashes with
  bcrypt >= 5). bcrypt rejects secrets longer than 72 bytes: truncate to
  72 bytes in both hash and verify.
- Expose \`hash_password\`, \`verify_password(password, password_hash | None) -> bool\`
  (None or ValueError → False), \`create_access_token(subject) -> str\`,
  \`decode_access_token(token) -> str | None\` from \`app/security.py\`.
- JWT bearer tokens (sub = principal id, secret/expiry via env).
- \`get_current_user\` dependency in \`app/deps.py\`: missing/invalid token →
  401 \`{"detail": "Not authenticated"}\` (exact body). Use
  \`HTTPBearer(auto_error=False)\` — the default \`auto_error\` raises **403**,
  which violates the contract. If the models use SQLAlchemy \`Uuid\` columns,
  parse \`uuid.UUID(sub)\` before \`db.get(...)\` — raw string binds against
  \`Uuid\` columns raise and 500.`
}

/** The invariant section of a router prompt (empty when none apply). */
function invariantSection(bp: BackendBlueprint, entityName: string): string {
  const relevant = bp.invariants.filter((inv) =>
    bp.routes.some(
      (r) => r.entity === entityName && r.invariantIds?.includes(inv.id),
    ),
  )
  if (relevant.length === 0) return ""
  const lines: string[] = [
    "",
    "### Invariants (truths that must hold at ALL times)",
    "",
  ]
  for (const inv of relevant) {
    if (inv.shape === "crossRowCount") {
      const c = inv.count!
      const bound =
        c.bound.kind === "field" ? `<row>.${c.bound.name}` : String(c.bound.value)
      lines.push(
        `- ${inv.name}: for every ${inv.entity} row — count of ${c.entity} rows whose`,
        `  ${c.refField} points at it must be ${c.op === "lt" ? "<" : "≤"} ${bound}.`,
        `  Enforced in create/update handlers of ${c.entity} and update handlers of`,
        `  ${inv.entity}, INSIDE the request transaction: apply the mutation, re-check`,
        `  the affected ${inv.entity} row, roll back and answer 409 on violation.`,
      )
    } else {
      lines.push(
        `- ${inv.name}: every ${inv.entity} row must satisfy the check tree below.`,
        `  Validate on create/update before committing.`,
      )
    }
  }
  lines.push(
    "",
    "Pinned violation outcome (exact body, row rolled back):",
    '409 `{"detail": "Invariant violated"}`',
    "",
    "Check trees (data, from the specification):",
    "",
    "```json",
    stableStringify(relevant.map((inv) => ({ id: inv.id, shape: inv.shape, check: inv.check, count: inv.count }))),
    "```",
    "",
  )
  return lines.join("\n")
}

/** The lifecycle section of a router prompt (empty when no transitions). */
function transitionSection(
  transitions: Array<{
    event: string
    path: string
    field: string
    from: string[]
    to: string
    guard?: unknown
    effects?: unknown[]
  }>,
): string {
  if (transitions.length === 0) return ""
  const hasEmits = transitions.some((tr) =>
    Array.isArray(tr.effects) &&
    tr.effects.some((e) => { const o = e as Record<string, unknown>; return o?.__effect === "emit" }),
  )
  const rows = transitions
    .map(
      (tr) =>
        `| ${tr.event} | POST ${tr.path} | ${tr.field} ∈ {${tr.from.join(", ")}}${tr.guard ? " + guard" : ""} | ${tr.field} = ${tr.to}${Array.isArray(tr.effects) && tr.effects.length > 0 ? " + effects" : ""} |`,
    )
    .join("\n")
  const lines = [
    "",
    "### Lifecycle transitions (state machine — the \"when it is allowed\" contract)",
    "",
    "| event | route | guard (current state) | sets |",
    "| --- | --- | --- | --- |",
    rows,
    "",
    "Implement each transition as an ATOMIC guarded update — the guard never",
    "leaves SQL, so two concurrent transitions of the same row serialize and",
    "the loser observes the guard failure:",
    "",
    "```sql",
    "UPDATE <table> SET <state_col> = '<to>'",
    "WHERE id = :id AND <state_col> IN ('<from>', ...) RETURNING *;",
    "```",
    "",
    "Pinned outcomes (exact bodies):",
    "- success → 200 with the updated row",
    "- row exists but wrong current state (or a failed guard) → 409 `{\"detail\": \"Invalid state\"}`",
    "- unknown id → 404 `{\"detail\": \"Not found\"}`",
    "",
    "The state field is server-controlled: it must NOT appear in create or",
    "update schemas (create assigns the initial state; update ignores it).",
  ]
  if (transitions.some((tr) => tr.guard)) {
    lines.push(
      "",
      "Guards (beyond the state check) are expression trees over row fields,",
      "constants and `requestTime` (the request's receipt time, naive UTC —",
      "evaluate it ONCE per request and bind it into the SQL comparison;",
      "never bake a timestamp into code). Guard data:",
      "",
      "```json",
      stableStringify(transitions.filter((tr) => tr.guard).map((tr) => ({ event: tr.event, guard: tr.guard }))),
      "```",
    )
  }
  if (transitions.some((tr) => Array.isArray(tr.effects) && tr.effects.length > 0)) {
    lines.push(
      "",
      "Effects run inside the transition's transaction, in declared order,",
      "all-or-nothing:",
      "- `set`: assign the field in the same UPDATE (value: a constant or",
      "  requestTime, naive UTC).",
      hasEmits
        ? "- `emit`: INSERT a row into the generated outbox table `events` —\n  columns EXACTLY (id TEXT uuid pk, event TEXT, payload TEXT holding a\n  JSON object, created_at datetime). The payload object's keys are the\n  effect's declared field names with the post-transition row's values."
        : "- (this entity emits no events)",
      "",
      "Effects data:",
      "",
      "```json",
      stableStringify(
        transitions
          .filter((tr) => Array.isArray(tr.effects) && tr.effects.length > 0)
          .map((tr) => ({ event: tr.event, effects: tr.effects })),
      ),
      "```",
    )
  }
  lines.push("")
  return lines.join("\n")
}

export function routerPrompt(
  bp: BackendBlueprint,
  ctx: TaskPromptInput,
  entityName: string,
): string {
  const entity = bp.entities.find((e) => e.name === entityName)!
  const routes = bp.routes.filter((r) => r.entity === entityName)
  const transitions = bp.routes
    .filter((r) => r.operation === "transition" && r.entity === entityName && r.transition)
    .map((r) => ({
      ...r.transition!,
      path: r.path,
      ...(r.transition!.guard !== undefined ? { guard: r.transition!.guard } : {}),
      ...(r.transition!.effects !== undefined ? { effects: r.transition!.effects } : {}),
    }))
  return `${taskHeader(`router: ${entityName}`, ctx.scope, ctx.context)}

Implement the API router for the **${entityName}** entity.

${SHARED_INVARIANTS}

## Entity
\`\`\`json
${stableStringify(entity)}
\`\`\`

## Routes for this router (the exact interface — no more, no less)
| method | path | success | auth | operation |
| --- | --- | --- | --- | --- |
${routeTable(routes)}
${transitionSection(transitions)}${invariantSection(bp, entityName)}
## Requirements
- Register count routes BEFORE any \`{id}\` route of the same prefix.
- Use the schemas from \`app/schemas.py\` and the models from \`app/models.py\`.
- \`list\`: every row ordered by created_at ascending; bare JSON array.
- \`create\`: 201 + stored row; validate that ref ids reference EXISTING
  rows — dangling refs are 404 \`{"detail": "Not found"}\`.
- \`update\`: partial PATCH; 200 + full row.
- \`delete\`: 204, empty body.
- \`count\`: \`{"count": <int>}\` (total rows).
- Unique violations → 409 \`{"detail": "Already exists"}\`.
${routes.some((r) => r.auth) ? "- Protected routes require the bearer token dependency (`get_current_user`)." : "- Every route here is public: no auth dependency."}`
}

export function authRouterPrompt(bp: BackendBlueprint, ctx: TaskPromptInput): string {
  const auth = bp.auth!
  const principal = bp.entities.find((e) => e.name === auth.principal)!
  return `${taskHeader("router: auth", ctx.scope, ctx.context)}

Implement the auth router (\`app/routers/auth.py\`).

${SHARED_INVARIANTS}

## Auth contract
\`\`\`json
${stableStringify(auth)}
\`\`\`

## Principal entity
\`\`\`json
${stableStringify(principal)}
\`\`\`

## Requirements
- \`POST ${auth.routes.find((r) => r.operation === "login")!.path}\`: body
  \`{"${auth.identityField}": ..., "password": ...}\` → 200
  \`{"access_token": "<jwt>", "token_type": "bearer"}\`; wrong identity or
  password → 401 \`{"detail": "Invalid credentials"}\` (identical for both —
  no user enumeration).
- \`POST ${auth.routes.find((r) => r.operation === "register")!.path}\`: body
  = principal fields + \`"password"\` (bcrypt-hash before storage) → 201
  with the principal row (never the hash). Duplicate identity → 409
  \`{"detail": "Already exists"}\`.
- \`GET ${auth.routes.find((r) => r.operation === "me")!.path}\`: bearer
  token → 200 principal row.
- Never serialize \`${auth.passwordColumn}\`.`
}

export function appPrompt(bp: BackendBlueprint, ctx: TaskPromptInput): string {
  const registrationOrder = bp.routes
    .filter((r) => r.entity !== undefined || r.operation === "login" || r.operation === "register" || r.operation === "me")
    .map((r) => `${r.method} ${r.path}`)
  return `${taskHeader("application wiring", ctx.scope, ctx.context)}

Implement the application factory (\`app/main.py\`).

${SHARED_INVARIANTS}

## Application
\`\`\`json
${stableStringify(bp.app)}
\`\`\`

## Complete route interface (register every one, nothing else)
${registrationOrder.map((r) => `- ${r}`).join("\n")}

## Requirements
- \`app/main.py\` MUST export
  \`create_app(database_url: str | None = None) -> FastAPI\` AND a
  module-level \`app = create_app()\`.
- Title \`${bp.app.title}\`, version \`${bp.app.version}\`.
- Include every router produced by previous tasks; count routes must be
  reachable (registered before same-prefix \`{id}\` routes — the routers
  already encode this, just include them).
- Create tables on startup against the resolved engine.
- Do not add extra routes: the conformance suite asserts strict OpenAPI
  equality (FastAPI's automatic /openapi.json and /docs are fine).`
}
