import type {
  AgentExecutionPlan,
  AgentExecutionTaskResult,
  AgentExecutionTask,
  ResolvedAgentExecutionTask,
} from "@spec/core"
import { runAgentExecutionSchedule } from "./scheduler"
import type { AgentExecutionScheduleFailure } from "./scheduler"
import { taskBranch } from "./plan"
import { validateAgentExecutionPlan } from "./validate"
import type {
  AgentExecutionContainerPort,
  AgentExecutionControlPlanePort,
  AgentExecutionRepositoryPort,
  MergeResult,
} from "./ports"

interface RuntimeResult extends AgentExecutionTaskResult {
  ok: boolean
}

export interface AgentExecutionReport {
  ok: boolean
  planFingerprint: string
  planRef: string
  planCommitSha: string
  tasks: AgentExecutionTaskResult[]
  skipped: string[]
  schedulerFailures: AgentExecutionScheduleFailure[]
}

export interface AgentExecutionOptions {
  repository: AgentExecutionRepositoryPort
  containers: AgentExecutionContainerPort
  controlPlane: AgentExecutionControlPlanePort
  concurrency?: number
  failFast?: boolean
  resume?: boolean
  onTaskStart?: (task: AgentExecutionTask) => void
  onTaskEnd?: (result: AgentExecutionTaskResult) => void
}

function isoNow(): string {
  return new Date().toISOString()
}

function prBody(plan: AgentExecutionPlan, task: ResolvedAgentExecutionTask, changedPaths: string[]): string {
  const dependencies = Object.entries(task.dependencyHeadShas)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([id, sha]) => `- ${id}: \`${sha}\``)
    .join("\n") || "- none"
  return `Generated by the GitHub-native spec agent execution DAG.

- Run: \`${plan.runId}\`
- Task: \`${task.id}\`
- Plan: \`${plan.fingerprint}\`
- Integration base: \`${task.baseSha}\`
- Environment: \`${task.environment.image}\`

Dependency commits:
${dependencies}

Owned and changed files:
${changedPaths.map((file) => `- \`${file}\``).join("\n")}

Downstream tasks may consume only this PR's pushed head SHA after required checks pass.`
}

function isSink(plan: AgentExecutionPlan, taskId: string): boolean {
  return !plan.tasks.some((task) => task.dependsOn.includes(taskId))
}

export async function runAgentExecutionPlan(
  plan: AgentExecutionPlan,
  options: AgentExecutionOptions,
): Promise<AgentExecutionReport> {
  const diagnostics = validateAgentExecutionPlan(plan)
  if (diagnostics.length > 0) {
    throw new Error(`invalid agent execution plan: ${diagnostics.map((item) => `${item.code}: ${item.message}`).join("; ")}`)
  }
  const publishedPlan = await options.repository.publishPlan(plan)

  // Sibling tasks finish concurrently, but the default branch accepts exactly
  // one linear history: merge-to-main integrations are serialized through one
  // promise chain so every push is a fast-forward of the previous merge.
  let mergeTail: Promise<unknown> = Promise.resolve()
  const mergeIntoDefaultBranch = (taskId: string, headSha: string): Promise<MergeResult> => {
    const run = mergeTail.then(() => options.repository.mergeIntoDefaultBranch(plan, taskId, headSha))
    mergeTail = run.catch(() => undefined)
    return run
  }

  const schedule = await runAgentExecutionSchedule<RuntimeResult>(
    plan.tasks,
    async (template, dependencyResults) => {
      const startedAt = isoNow()
      const branch = taskBranch(plan, template.id)
      let workspace: string | undefined
      let resumeHeadSha: string | undefined
      try {
        const base = await options.repository.materializeIntegrationBase(plan, template.id, dependencyResults)
        const resolved: ResolvedAgentExecutionTask = {
          ...template,
          runId: plan.runId,
          repository: plan.repository,
          baseSha: base.sha,
          dependencyHeadShas: Object.fromEntries(dependencyResults.map((result) => [result.taskId, result.headSha!])),
          baseRef: base.ref,
          branch,
          environment: plan.environment,
          acceptance: template.acceptance ?? plan.acceptance,
        }
        const acceptance = {
          commands: resolved.acceptance.commands,
          ...(resolved.workingDirectory ? { workingDirectory: resolved.workingDirectory } : {}),
        }
        const pullRequestFor = (changedPaths: string[]) => options.controlPlane.upsertPullRequest({
          repository: plan.repository,
          head: branch,
          base: isSink(plan, template.id) ? plan.defaultBranch : base.ref,
          title: isSink(plan, template.id)
            ? `spec agent execution run ${plan.runId}`
            : `spec(${template.id}): ${template.objective}`,
          body: prBody(plan, resolved, changedPaths),
        })
        const checksFor = (pullRequestNumber: number, expectedHeadSha: string) => options.controlPlane.waitForChecks({
          repository: plan.repository,
          pullRequest: pullRequestNumber,
          requiredChecks: resolved.acceptance.requiredChecks,
          expectedHeadSha,
          acceptance,
        })
        const landedOnDefaultBranch = async (headSha: string) => {
          if (plan.mergePolicy !== "merge-to-main") return { status: "review" as const, mergedSha: undefined }
          const merged = await mergeIntoDefaultBranch(template.id, headSha)
          return { status: "merged" as const, mergedSha: merged.sha }
        }

        const remoteHead = await options.repository.remoteHead(branch)
        if (remoteHead) {
          const provenance = await options.repository.verifyCommitProvenance(remoteHead, branch, base.sha, plan, template.id)
          if (!provenance) throw new Error(`remote branch ${branch} exists without matching run/task/fingerprint provenance`)
          const existingPr = await pullRequestFor(template.scope)
          const checks = await checksFor(existingPr.number, remoteHead)
          if (checks.every((check) => check.status === "success")) {
            const landed = await landedOnDefaultBranch(remoteHead)
            return {
              taskId: template.id,
              ok: true,
              status: landed.status,
              ...(landed.mergedSha ? { mergedSha: landed.mergedSha } : {}),
              branch,
              integrationBaseSha: base.sha,
              headSha: remoteHead,
              pullRequest: { number: existingPr.number, url: existingPr.url },
              checks,
              startedAt,
              completedAt: isoNow(),
            }
          }
          if (!options.resume) {
            throw new Error(`remote task branch ${branch} has failing or incomplete required checks; rerun generate with --resume to create a retry checkpoint`)
          }
          resumeHeadSha = remoteHead
        }
        if (options.resume) {
          // Absence is a normal resume state: this task had not reached a
          // durable commit before its executor disappeared.
        }

        workspace = await options.repository.createWorkspace(resolved, resumeHeadSha)
        const execution = await options.containers.execute(resolved, workspace)
        if (!execution.ok) throw new Error(execution.error ?? `container execution failed for ${template.id}`)
        const committed = await options.repository.commitAndPush(
          resolved,
          workspace,
          plan.fingerprint,
          { allowEmpty: resumeHeadSha !== undefined },
        )
        const pullRequest = await pullRequestFor(committed.changedPaths)
        const githubChecks = await checksFor(pullRequest.number, committed.headSha)
        const ok = githubChecks.every((check) => check.status === "success")
        let status: RuntimeResult["status"] = ok ? "review" : "failure"
        let mergedSha: string | undefined
        if (ok) {
          const landed = await landedOnDefaultBranch(committed.headSha)
          status = landed.status
          if (landed.mergedSha) mergedSha = landed.mergedSha
        }
        if (ok && plan.mergePolicy === "merge-queue" && isSink(plan, template.id)) {
          await options.controlPlane.enqueuePullRequest(plan.repository, pullRequest.number)
        }
        return {
          taskId: template.id,
          ok,
          status,
          ...(mergedSha ? { mergedSha } : {}),
          branch,
          integrationBaseSha: base.sha,
          headSha: committed.headSha,
          pullRequest: { number: pullRequest.number, url: pullRequest.url },
          checks: [...execution.checks, ...githubChecks],
          startedAt,
          completedAt: isoNow(),
          costUsd: execution.costUsd,
        }
      } catch (error) {
        return {
          taskId: template.id,
          ok: false,
          status: "failure",
          branch,
          checks: [],
          startedAt,
          completedAt: isoNow(),
          diagnostics: [{
            code: "AGENT_EXECUTION_TASK_FAILED",
            level: "error",
            message: error instanceof Error ? error.message : String(error),
            details: { task: template.id, runId: plan.runId },
          }],
        }
      } finally {
        if (workspace) {
          try {
            await options.repository.removeWorkspace(workspace)
          } catch {
            // Cleanup must never erase a durable push/PR result or allow the
            // scheduler to return while sibling workers are still active.
          }
        }
      }
    },
    {
      concurrency: options.concurrency,
      failFast: options.failFast,
      onTaskStart: options.onTaskStart,
      onTaskEnd: options.onTaskEnd,
    },
  )
  return {
    ok: schedule.ok,
    planFingerprint: plan.fingerprint,
    planRef: publishedPlan.ref,
    planCommitSha: publishedPlan.sha,
    tasks: schedule.results.map(({ ok: _ok, ...result }) => result),
    skipped: schedule.skipped,
    schedulerFailures: schedule.failures,
  }
}
